import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import ExitModal from "@/components/modals/ExitModal";
import HeartModal from "@/components/modals/HeartsModal";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lingo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <link rel="icon" href="favicon.svg" />
        <body className={font.className}>
          <Toaster />
          <ExitModal />
          <HeartModal />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
